#!/bin/bash

packages=(
        ./upload/
        ./upload/concurrent/
        ./upload/metadata/
        ./upload/progress/
        ./vhdcore/
        ./vhdcore/bat/
        ./vhdcore/block/
        ./vhdcore/block/bitmap/
        ./vhdcore/common/
        ./vhdcore/diskstream/
        ./vhdcore/footer/
        ./vhdcore/header/
        ./vhdcore/header/parentlocator/
        ./vhdcore/innererror/
        ./vhdcore/reader/
        ./vhdcore/validator/
        ./vhdcore/vhdfile/
        ./vhdcore/writer/
    )

for i in ${packages[@]}; do
        gofmt -w ${i}*.go
done

for i in ${packages[@]}; do
        golint ${i}
done

go build -v "${packages[@]}"
go build -v *.go

exit 0